# Relevant Imports

In [1]:
# Cell 1: Relevant Imports
import pandas as pd
import numpy as np
from datetime import datetime

# Preprocessing

In [2]:
# Cell 2: Load the CSV file
# Assuming the file is named 'sp500_news_simple_2024_AAPL.csv' and is in the current directory
df = pd.read_csv('sp500_news_simple_2024_XOM.csv')
# Display the first few rows to inspect the data
df.head()

,time_published,title,summary
0,2024-01-02 12:05:00,3 Dimensional Mutual Funds for Consistent Returns,"Below, we share with you three top-ranked Dime..."
1,2024-01-02 12:20:33,"ExxonMobil Reportedly Bids Iraq Farewell, Petr...",Exxon Mobil Corp XOM has reportedly exited the...
2,2024-01-02 13:00:00,Analysts Predict Surprising New 'Magnificent 7...,"Forget the ""Magnificent Seven"" stocks that dro..."
3,2024-01-02 13:00:07,"Down 9% Since The Beginning Of 2023, What Shou...",After a 9% decline since the beginning of 2023...
4,2024-01-02 15:24:00,This Giant Oil Stock Is My Top Dividend Pick f...,"Exxon's strong dividends, its record of strong..."

In [3]:
# Cell 3: Extract date from 'time_published' column without timestamp
# Convert 'time_published' to datetime format
df['time_published'] = pd.to_datetime(df['time_published'])
# Extract date in DD/MM/YYYY format
df['date'] = df['time_published'].dt.strftime('%d/%m/%Y')
# Display the updated DataFrame
df.head()

,time_published,title,summary,date
0,2024-01-02 12:05:00,3 Dimensional Mutual Funds for Consistent Returns,"Below, we share with you three top-ranked Dime...",02/01/2024
1,2024-01-02 12:20:33,"ExxonMobil Reportedly Bids Iraq Farewell, Petr...",Exxon Mobil Corp XOM has reportedly exited the...,02/01/2024
2,2024-01-02 13:00:00,Analysts Predict Surprising New 'Magnificent 7...,"Forget the ""Magnificent Seven"" stocks that dro...",02/01/2024
3,2024-01-02 13:00:07,"Down 9% Since The Beginning Of 2023, What Shou...",After a 9% decline since the beginning of 2023...,02/01/2024
4,2024-01-02 15:24:00,This Giant Oil Stock Is My Top Dividend Pick f...,"Exxon's strong dividends, its record of strong...",02/01/2024

In [4]:
# Cell 4: Select only the required columns: date, title, and summary (assuming 'summary' is the content)
# Rename 'summary' to 'content' if needed for clarity
df_cleaned = df[['date', 'title', 'summary']].rename(columns={'summary': 'content'})
# Display the cleaned DataFrame
df_cleaned.head()

,date,title,content
0,02/01/2024,3 Dimensional Mutual Funds for Consistent Returns,"Below, we share with you three top-ranked Dime..."
1,02/01/2024,"ExxonMobil Reportedly Bids Iraq Farewell, Petr...",Exxon Mobil Corp XOM has reportedly exited the...
2,02/01/2024,Analysts Predict Surprising New 'Magnificent 7...,"Forget the ""Magnificent Seven"" stocks that dro..."
3,02/01/2024,"Down 9% Since The Beginning Of 2023, What Shou...",After a 9% decline since the beginning of 2023...
4,02/01/2024,This Giant Oil Stock Is My Top Dividend Pick f...,"Exxon's strong dividends, its record of strong..."

In [5]:
# Cell 5: Optional - Handle any missing values or duplicates if necessary
# Drop rows with missing values (if any)
df_cleaned = df_cleaned.dropna()
# Remove duplicates (if any)
df_cleaned = df_cleaned.drop_duplicates()
# Display info about the cleaned DataFrame
df_cleaned.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1942 entries, 0 to 1948
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   date     1942 non-null   object
 1   title    1942 non-null   object
 2   content  1942 non-null   object
dtypes: object(3)
memory usage: 60.7+ KB

In [6]:
# Cell 6: Save the cleaned data to a new CSV file
output_filename = 'cleaned_sp500_news_2024_XOM.csv'
df_cleaned.to_csv(output_filename, index=False)
print(f"Cleaned data saved to {output_filename}")

Cleaned data saved to cleaned_sp500_news_2024_XOM.csv